# Generated by Django 5.1.2 on 2025-11-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Holmi', 'verbose_name_plural': 'Holmik'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'Holmi kép', 'verbose_name_plural': 'Holmi képek'},
        ),
    ]
