# Generated by Django 5.1.2 on 2025-11-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loan_state_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('REQUESTED', 'Igénylve'), ('ACCEPTED', 'Elfoagdva'), ('HANDED_OVER', 'Átadva'), ('RETURNED', 'Visszaadva'), ('DECLINED', 'Elutasítva'), ('CANCELLED', 'Lemondva')], default='REQUESTED', max_length=20),
        ),
    ]
